### ISSUE TITLE
can not run starter.sh

### ISSUE THREAD

**Issue by Light--** [hav4ik/Hydra#3]
```
$ ./starter.sh naive 50
EXPERIMENT: naive
  - device: TITAN Xp
  - output: ~/data/out
Using downloaded and verified file: /home/user1/data/torchvision/MNIST/raw/train-images-idx3-ubyte.gz
Extracting /home/user1/data/torchvision/MNIST/raw/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to /home/user1/data/torchvision/MNIST/raw/train-labels-idx1-ubyte.gz
 57%|\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u258e                                              | 16384/28881 [02:04<00:57, 215.98it/s]Extracting /home/user1/data/torchvision/MNIST/raw/train-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "src/run.py", line 136, in <module>
    verbose=args.verbose)
  File "src/run.py", line 80, in run
    cfg, n_workers, verbose)
  File "src/run.py", line 20, in import_data_loaders
    dataset_config['name'], dataset_config['kwargs'])
  File "/home/user1/multiTaskCNN/simple_mt/Hydra/src/datasets/__init__.py", line 11, in load_dataset
    return dataset_def(**dataset_kwargs)
  File "/home/user1/multiTaskCNN/simple_mt/Hydra/src/datasets/toy.py", line 26, in toy
    download=True, transform=composed_transform)
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 68, in __init__
    self.download()
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 146, in download
    self.extract_gzip(gzip_path=file_path, remove_finished=True)
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 128, in extract_gzip
    out_f.write(zip_f.read())
  File "/home/user1/miniconda3/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/home/user1/miniconda3/lib/python3.7/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
 57%|\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u258e                                              | 16384/28881 [02:04<01:34, 131.60it/s]
```

**Comment by hav4ik** [comment]
Weights download was performed using `torchvision`, so it's not a problem of this repo. A related SO thread:
https://stackoverflow.com/questions/40877781/eoferror-compressed-file-ended-before-the-end-of-stream-marker-was-reached-mn
